src/Entity/Ingredient.php
<?php

namespace App\Entity;

use App\Repository\IngredientRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=IngredientRepository::class)
 */
class Ingredient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Recipe::class, inversedBy="recipe_ingredient")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ingredient_recipe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ingredient_name;

   /**
     * @ORM\Column(type="string", length=75)
     */ 
    private $quantity;

    // /**
    //  * Constructor
    //  */ 
    // public function __construct(){
    //     $this->createdAt = new \Integer();
    // }

    public function __toString(){
        return $this->ingredient_name; // Remplacer champ par une propriété "string" de l'entité
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIngredientRecipe(): ?Recipe
    {
        return $this->ingredient_recipe;
    }

    public function setIngredientRecipe(?Recipe $ingredient_recipe): self
    {
        $this->ingredient_recipe = $ingredient_recipe;

        return $this;
    }

    public function getIngredientName(): ?string
    {
        return $this->ingredient_name;
    }

    public function setIngredientName(string $ingredient_name): self
    {
        $this->ingredient_name = $ingredient_name;

        return $this;
    }

    public function getQuantity(): ?string
    {
        return $this->quantity;
    }

    public function setQuantity(string $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }
}

src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecipeRepository::class)
 */
class Recipe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="user_recipe")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipe_user;

    /**
     * @ORM\OneToMany(targetEntity=Ingredient::class, mappedBy="ingredient_recipe")
     */
    private $recipe_ingredient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $recipe_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_person;

    /**
     * @ORM\OneToMany(targetEntity=Step::class, mappedBy="step_recipe")
     */
    private $recipe_step;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="comment_recipe")
     */
    private $recipe_comment;

    /**
     * @ORM\OneToMany(targetEntity=Mark::class, mappedBy="mark_recipe")
     */
    private $recipe_mark;

    /**
     * @ORM\Column(type="integer")
     */
    private $preparation_time;

    /**
     * @ORM\Column(type="integer")
     */
    private $cooking_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    public function __toString(){
        return $this->recipe_name; // Remplacer champ par une propriété "string" de l'entité
    }

    public function __construct()
    {
        $this->recipe_ingredient = new ArrayCollection();
        $this->recipe_step = new ArrayCollection();
        $this->recipe_comment = new ArrayCollection();
        $this->recipe_mark = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRecipeUser(): ?User
    {
        return $this->recipe_user;
    }

    public function setRecipeUser(?User $recipe_user): self
    {
        $this->recipe_user = $recipe_user;

        return $this;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getRecipeIngredient(): Collection
    {
        return $this->recipe_ingredient;
    }

    public function addRecipeIngredient(Ingredient $recipeIngredient): self
    {
        if (!$this->recipe_ingredient->contains($recipeIngredient)) {
            $this->recipe_ingredient[] = $recipeIngredient;
            $recipeIngredient->setIngredientRecipe($this);
        }

        return $this;
    }

    public function removeRecipeIngredient(Ingredient $recipeIngredient): self
    {
        if ($this->recipe_ingredient->removeElement($recipeIngredient)) {
            // set the owning side to null (unless already changed)
            if ($recipeIngredient->getIngredientRecipe() === $this) {
                $recipeIngredient->setIngredientRecipe(null);
            }
        }

        return $this;
    }

    public function getRecipeName(): ?string
    {
        return $this->recipe_name;
    }

    public function setRecipeName(string $recipe_name): self
    {
        $this->recipe_name = $recipe_name;

        return $this;
    }

    public function getNumberPerson(): ?int
    {
        return $this->number_person;
    }

    public function setNumberPerson(int $number_person): self
    {
        $this->number_person = $number_person;

        return $this;
    }

    /**
     * @return Collection<int, Step>
     */
    public function getRecipeStep(): Collection
    {
        return $this->recipe_step;
    }

    public function addRecipeStep(Step $recipeStep): self
    {
        if (!$this->recipe_step->contains($recipeStep)) {
            $this->recipe_step[] = $recipeStep;
            $recipeStep->setStepRecipe($this);
        }

        return $this;
    }

    public function removeRecipeStep(Step $recipeStep): self
    {
        if ($this->recipe_step->removeElement($recipeStep)) {
            // set the owning side to null (unless already changed)
            if ($recipeStep->getStepRecipe() === $this) {
                $recipeStep->setStepRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getRecipeComment(): Collection
    {
        return $this->recipe_comment;
    }

    public function addRecipeComment(Comment $recipeComment): self
    {
        if (!$this->recipe_comment->contains($recipeComment)) {
            $this->recipe_comment[] = $recipeComment;
            $recipeComment->setCommentRecipe($this);
        }

        return $this;
    }

    public function removeRecipeComment(Comment $recipeComment): self
    {
        if ($this->recipe_comment->removeElement($recipeComment)) {
            // set the owning side to null (unless already changed)
            if ($recipeComment->getCommentRecipe() === $this) {
                $recipeComment->setCommentRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Mark>
     */
    public function getRecipeMark(): Collection
    {
        return $this->recipe_mark;
    }

    public function addRecipeMark(Mark $recipeMark): self
    {
        if (!$this->recipe_mark->contains($recipeMark)) {
            $this->recipe_mark[] = $recipeMark;
            $recipeMark->setMarkRecipe($this);
        }

        return $this;
    }

    public function removeRecipeMark(Mark $recipeMark): self
    {
        if ($this->recipe_mark->removeElement($recipeMark)) {
            // set the owning side to null (unless already changed)
            if ($recipeMark->getMarkRecipe() === $this) {
                $recipeMark->setMarkRecipe(null);
            }
        }

        return $this;
    }

    public function getPreparationTime(): ?int
    {
        return $this->preparation_time;
    }

    public function setPreparationTime(int $preparation_time): self
    {
        $this->preparation_time = $preparation_time;

        return $this;
    }

    public function getCookingTime(): ?int
    {
        return $this->cooking_time;
    }

    public function setCookingTime(int $cooking_time): self
    {
        $this->cooking_time = $cooking_time;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Recipe;
use App\Entity\Ingredient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('recipe_name', TextType::class)
            ->add('number_person', IntegerType::class)
            ->add('preparation_time', IntegerType::class)
            ->add('cooking_time', IntegerType::class)
            ->add('picture', FileType::class, [
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize'=>'16384k',
                        'maxSizeMessage'=>'Taille de fichier trop grande',
                        'mimeTypes'=>[
                            'image/jpeg',
                            'image/png',
                            'image/svg',
                        ],
                        'mimeTypesMessage'=>'Extension de fichier invalide',
                    ])
                    ],
                'attr'=>[
                    'class'=>'form-control',
                ],
                'data_class'=>null,

            ])
            
            ->add('recipe_ingredient', EntityType::class, [
                'label' => "Ingredient :",
                'class' => Ingredient::class,
                'choice_label'=> 'ingredient_name',
                'multiple' => false,
                'expanded' => true,
                'mapped' => false,
            ])
            
            ->add('recipe_step')

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use Twig\Environment;
use App\Entity\Recipe;
use App\Entity\Comment;
use App\Form\RecipeType;
use App\Form\CommentType;
use App\Service\FileUploader;
use App\Repository\StepRepository;
use App\Repository\UserRepository;
use App\Repository\RecipeRepository;
use App\Repository\CommentRepository;
use App\Repository\IngredientRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/recipe")
 */
class RecipeController extends AbstractController
{     
    private $twig;
    private $entityManager;

    public function __construct(Environment $twig, EntityManagerInterface $entityManager)
     {
        
        $this->twig = $twig;
        $this->entityManager = $entityManager;
     }

    /**
     * @Route("/", name="app_recipe_index", methods={"GET"})
     */
    public function index(RecipeRepository $recipeRepository, StepRepository $stepRepository, IngredientRepository $ingredientRepository, UserRepository $userRepository, Request $request): Response
    {
        return $this->render('recipe/index.html.twig', [
            'recipes' => $recipeRepository->findAll(),
            'steps' => $stepRepository->findAll(),
            'ingredients' => $ingredientRepository->findAll(),
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_recipe_new", methods={"GET", "POST"})
     */
    public function new(Request $request, RecipeRepository $recipeRepository, FileUploader $fileUploader ): Response
    {
        $recipe = new Recipe();
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $picture = $form->get('picture')->getData();
            if($picture) {
                $fileName = $fileUploader->upload($picture);
                $recipe->setPicture($fileName);
                }

            $user=$this->getUser();
            $recipe->setRecipeUser($user);
            $recipeRepository->add($recipe, true);

            return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('recipe/new.html.twig', [
            'recipe' => $recipe,
            'form' => $form,
        ]);


    }

    /**
     * @Route("/{id}", name="app_recipe_show", methods={"GET", "POST"})
     */
    public function show(Recipe $recipe, StepRepository $stepRepository, IngredientRepository $ingredientRepository, Request $request, CommentRepository $commentRepository, EntityManagerInterface $entityManager ): Response
    {
        $comment = new Comment();
        $commentForm = $this->createForm(CommentType::class, $comment);
        $commentForm->handleRequest($request);
        
        return $this->render('recipe/show.html.twig', [
            'recipe' => $recipe,
            // 'step' => $stepRepository,
            // 'ingredient' => $ingredientRepository,
            // 'comment' => $commentRepository,
            // 'comment_form' => $commentForm->createView(),
        ]);
        
        //     if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            //         dump("$comment");
    //     $comment->setRecipe($recipe);
    //     $comment->setCommentUser($user);
    
    //     $commentRepository->add($comment, true);
    
    //     $this->entityManager->persist($comment);
    //     $this->entityManager->flush();
    
    //     $user=$this->getUser();
    
    
    //     $this->addFlash('message', 'Votre commentaire a bien été envoyé');
    
    //         return $this->redirectToRoute('recipe', ['id' => 'app_recipe_show'->getId()], Response::HTTP_SEE_OTHER);
    // }

    // $response = $this->forward('App\Controller\CommentController::new', [
    //     'comment' => $comment,
    // ]);
    
    // return $response;
}

    /**
     * @Route("/{id}/edit", name="app_recipe_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Recipe $recipe, RecipeRepository $recipeRepository): Response
    {
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recipeRepository->add($recipe, true);

            return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('recipe/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_recipe_delete", methods={"POST"})
     */
    public function delete(Request $request, Recipe $recipe, RecipeRepository $recipeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->request->get('_token'))) {
            $recipeRepository->remove($recipe, true);
        }

        return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/recipe/_delete_form.html.twig
<form method="post" action="{{ path('app_recipe_delete', {'id': recipe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recipe/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/recipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recipe{% endblock %}

{% block body %}
    <h1>Edit Recipe</h1>

    {{ include('recipe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_recipe_index') }}">back to list</a>

    {{ include('recipe/_delete_form.html.twig') }}
{% endblock %}

templates/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe index{% endblock %}

{% block body %}
    <h1>Recipe index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Recipe_name</th>
                <th>Number_person</th>
                <th>Preparation_time</th>
                <th>Cooking_time</th>
                <th>Picture</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for recipe in recipes %}
            <tr>
                <td>{{ recipe.id }}</td>
                <td>{{ recipe.recipeName }}</td>
                <td>{{ recipe.numberPerson }}</td>
                <td>{{ recipe.preparationTime }}</td>
                <td>{{ recipe.cookingTime }}</td>
                <td>{{ recipe.picture }}</td>
                <td>
                    <a href="{{ path('app_recipe_show', {'id': recipe.id}) }}">show</a>
                    <a href="{{ path('app_recipe_edit', {'id': recipe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_recipe_new') }}">Create new</a>
{% endblock %}

templates/recipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Recipe{% endblock %}

{% block body %}
    <h1>Create new Recipe</h1>

    {{ include('recipe/_form.html.twig') }}

    <a href="{{ path('app_recipe_index') }}">back to list</a>
{% endblock %}

templates/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe{% endblock %}

{% block body %}
    <h1>Recipe</h1>

    <table class="table">
        <tbody>
            <tr>
                <td><img src="{{app.request.basepath}}/uploads/images/{{recipe.picture}}"></td>
            </tr>
            <tr>
                <th>Recipe_name</th>
                <td>{{ recipe.recipeName }}</td>
            </tr>
            <tr>
                <th>Number_person</th>
                <td>{{ recipe.numberPerson }}</td>
            </tr>
            <tr>
                <th>Preparation_time</th>
                <td>{{ recipe.preparationTime }} min</td>
            </tr>
            <tr>
                <th>Cooking_time</th>
                <td>{{ recipe.cookingTime }} min</td>
            </tr>
            <tr>
                <th>Ingredient</th>
                {# <td>{{ recipe.ingredientRecipe.ingredientName }}</td> #}
            </tr>
            <tr>
                <th>Step</th>

            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ recipe.recipeUser.pseudo }}</td>
            </tr>
        </tbody>
    </table>

    <div>
        <h2>Commentaires</h2>
        
        <h2>Ajouter un commentaire</h2>
        {# {{ form(comment_form) }} #}
        
    </div>


    <a href="{{ path('app_recipe_index') }}">back to list</a>

    {# <a href="{{ path('app_recipe_edit', {'id': recipe.id}) }}">edit</a> #}

    {{ include('recipe/_delete_form.html.twig') }}
{% endblock %}