src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecipeRepository::class)
 */
class Recipe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="user_recipe")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipe_user;

    /**
     * @ORM\OneToMany(targetEntity=Ingredient::class, mappedBy="ingredient_recipe")
     */
    private $recipe_ingredient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $recipe_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_person;

    /**
     * @ORM\OneToMany(targetEntity=Step::class, mappedBy="step_recipe")
     */
    private $recipe_step;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="comment_recipe")
     */
    private $recipe_comment;

    /**
     * @ORM\OneToMany(targetEntity=Mark::class, mappedBy="mark_recipe")
     */
    private $recipe_mark;

    /**
     * @ORM\Column(type="integer")
     */
    private $preparation_time;

    /**
     * @ORM\Column(type="integer")
     */
    private $cooking_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    public function __toString(){
        return $this->recipe_name; // Remplacer champ par une propriété "string" de l'entité
    }

    public function __construct()
    {
        $this->recipe_ingredient = new ArrayCollection();
        $this->recipe_step = new ArrayCollection();
        $this->recipe_comment = new ArrayCollection();
        $this->recipe_mark = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRecipeUser(): ?User
    {
        return $this->recipe_user;
    }

    public function setRecipeUser(?User $recipe_user): self
    {
        $this->recipe_user = $recipe_user;

        return $this;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getRecipeIngredient(): Collection
    {
        return $this->recipe_ingredient;
    }

    public function addRecipeIngredient(Ingredient $recipeIngredient): self
    {
        if (!$this->recipe_ingredient->contains($recipeIngredient)) {
            $this->recipe_ingredient[] = $recipeIngredient;
            $recipeIngredient->setIngredientRecipe($this);
        }

        return $this;
    }

    public function removeRecipeIngredient(Ingredient $recipeIngredient): self
    {
        if ($this->recipe_ingredient->removeElement($recipeIngredient)) {
            // set the owning side to null (unless already changed)
            if ($recipeIngredient->getIngredientRecipe() === $this) {
                $recipeIngredient->setIngredientRecipe(null);
            }
        }

        return $this;
    }

    public function getRecipeName(): ?string
    {
        return $this->recipe_name;
    }

    public function setRecipeName(string $recipe_name): self
    {
        $this->recipe_name = $recipe_name;

        return $this;
    }

    public function getNumberPerson(): ?int
    {
        return $this->number_person;
    }

    public function setNumberPerson(int $number_person): self
    {
        $this->number_person = $number_person;

        return $this;
    }

    /**
     * @return Collection<int, Step>
     */
    public function getRecipeStep(): Collection
    {
        return $this->recipe_step;
    }

    public function addRecipeStep(Step $recipeStep): self
    {
        if (!$this->recipe_step->contains($recipeStep)) {
            $this->recipe_step[] = $recipeStep;
            $recipeStep->setStepRecipe($this);
        }

        return $this;
    }

    public function removeRecipeStep(Step $recipeStep): self
    {
        if ($this->recipe_step->removeElement($recipeStep)) {
            // set the owning side to null (unless already changed)
            if ($recipeStep->getStepRecipe() === $this) {
                $recipeStep->setStepRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getRecipeComment(): Collection
    {
        return $this->recipe_comment;
    }

    public function addRecipeComment(Comment $recipeComment): self
    {
        if (!$this->recipe_comment->contains($recipeComment)) {
            $this->recipe_comment[] = $recipeComment;
            $recipeComment->setCommentRecipe($this);
        }

        return $this;
    }

    public function removeRecipeComment(Comment $recipeComment): self
    {
        if ($this->recipe_comment->removeElement($recipeComment)) {
            // set the owning side to null (unless already changed)
            if ($recipeComment->getCommentRecipe() === $this) {
                $recipeComment->setCommentRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Mark>
     */
    public function getRecipeMark(): Collection
    {
        return $this->recipe_mark;
    }

    public function addRecipeMark(Mark $recipeMark): self
    {
        if (!$this->recipe_mark->contains($recipeMark)) {
            $this->recipe_mark[] = $recipeMark;
            $recipeMark->setMarkRecipe($this);
        }

        return $this;
    }

    public function removeRecipeMark(Mark $recipeMark): self
    {
        if ($this->recipe_mark->removeElement($recipeMark)) {
            // set the owning side to null (unless already changed)
            if ($recipeMark->getMarkRecipe() === $this) {
                $recipeMark->setMarkRecipe(null);
            }
        }

        return $this;
    }

    public function getPreparationTime(): ?int
    {
        return $this->preparation_time;
    }

    public function setPreparationTime(int $preparation_time): self
    {
        $this->preparation_time = $preparation_time;

        return $this;
    }

    public function getCookingTime(): ?int
    {
        return $this->cooking_time;
    }

    public function setCookingTime(int $cooking_time): self
    {
        $this->cooking_time = $cooking_time;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=75)
     */
    private $gender;

    /**
     * @ORM\Column(type="date")
     */
    private $date_of_birth;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Recipe::class, mappedBy="recipe_user")
     */
    private $user_recipe;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="comment_user")
     */
    private $user_comment;

    /**
     * @ORM\OneToMany(targetEntity=Mark::class, mappedBy="mark_user")
     */
    private $user_mark;

    public function __toString(){
        return $this->pseudo; // Remplacer champ par une propriété "string" de l'entité
    }

    public function __construct()
    {
        $this->user_recipe = new ArrayCollection();
        $this->user_comment = new ArrayCollection();
        $this->user_mark = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Recipe>
     */
    public function getUserRecipe(): Collection
    {
        return $this->user_recipe;
    }

    public function addUserRecipe(Recipe $userRecipe): self
    {
        if (!$this->user_recipe->contains($userRecipe)) {
            $this->user_recipe[] = $userRecipe;
            $userRecipe->setRecipeUser($this);
        }

        return $this;
    }

    public function removeUserRecipe(Recipe $userRecipe): self
    {
        if ($this->user_recipe->removeElement($userRecipe)) {
            // set the owning side to null (unless already changed)
            if ($userRecipe->getRecipeUser() === $this) {
                $userRecipe->setRecipeUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getUserComment(): Collection
    {
        return $this->user_comment;
    }

    public function addUserComment(Comment $userComment): self
    {
        if (!$this->user_comment->contains($userComment)) {
            $this->user_comment[] = $userComment;
            $userComment->setCommentUser($this);
        }

        return $this;
    }

    public function removeUserComment(Comment $userComment): self
    {
        if ($this->user_comment->removeElement($userComment)) {
            // set the owning side to null (unless already changed)
            if ($userComment->getCommentUser() === $this) {
                $userComment->setCommentUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Mark>
     */
    public function getUserMark(): Collection
    {
        return $this->user_mark;
    }

    public function addUserMark(Mark $userMark): self
    {
        if (!$this->user_mark->contains($userMark)) {
            $this->user_mark[] = $userMark;
            $userMark->setMarkUser($this);
        }

        return $this;
    }

    public function removeUserMark(Mark $userMark): self
    {
        if ($this->user_mark->removeElement($userMark)) {
            // set the owning side to null (unless already changed)
            if ($userMark->getMarkUser() === $this) {
                $userMark->setMarkUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class)
            // ->add('roles')
            ->add('password', PasswordType::class)
            ->add('pseudo', TextType::class)
            ->add('gender', TextType::class)
            ->add('date_of_birth', BirthdayType::class)
            ->add('isVerified')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="app_user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_user_new", methods={"GET", "POST"})
     */
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_user_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Pseudo</th>
                <th>Gender</th>
                <th>Date_of_birth</th>
                <th>IsVerified</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.pseudo }}</td>
                <td>{{ user.gender }}</td>
                <td>{{ user.dateOfBirth ? user.dateOfBirth|date('Y-m-d') : '' }}</td>
                <td>{{ user.isVerified ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

templates/user/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}

<div>
    <p>Pseudo : {{ user.pseudo }}</p>
    <p>Adresse mail : {{ user.email }}</p>
    <p>Genre : {{ user.gender }}</p>
    <p>Date de naissance : {{ user.dateOfBirth | date('d/m/Y') }}</p>

</div>

<div>
    <p>Historique des recettes :
        {% for recipe in recipes %}
            {{ recipe.recipeName }}
        {% endfor %}
    </p>

</div>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ user.pseudo }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ user.gender }}</td>
            </tr>
            <tr>
                <th>Date_of_birth</th>
                <td>{{ user.dateOfBirth ? user.dateOfBirth|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>IsVerified</th>
                <td>{{ user.isVerified ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_user_index') }}">back to list</a>

    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}